name: Deploy RDS to ECS

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-backend-rds:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update ECS service with new image
        run: |
          TAG=$(make tag TARGET_FOLDER=backend_rds)
          aws ecs update-service \
            --cluster art_gallery_ecs_cluster \
            --service ecs_service_rds \
            --force-new-deployment \
            --image "$TAG"
